# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: gavriel10donovan@gmail.com
author_name: G30TR1X
contract_name: supply_chain_tracer
deployment_language: python
preset_name: starter
project_name: supply_chain_tracer-contracts

